version: '3.8'

services:
  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./mcp-server/src:/app/src
      - ./mcp-server/.env:/app/.env
    networks:
      - contract-manager
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  # Future services will be added here:
  # mcp-inspector:
  #   image: modelcontextprotocol/inspector
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - contract-manager

  # auth-server:
  #   build: ./auth-server
  #   ports:
  #     - "3001:3001"
  #   networks:
  #     - contract-manager

  # web-ui:
  #   build: ./web-ui
  #   ports:
  #     - "3002:3002"
  #   networks:
  #     - contract-manager

networks:
  contract-manager:
    driver: bridge

volumes:
  postgres_data:
    # For future database storage
